FROM php:8.4-cli

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git unzip curl libzip-dev zip \
    && docker-php-ext-install pdo pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

# SQLite作成
RUN touch database/database.sqlite

# 権限
RUN chmod -R 777 storage bootstrap/cache database

# ビルド時キャッシュ削除
RUN php artisan config:clear || true
RUN php artisan cache:clear || true
RUN php artisan route:clear || true
RUN php artisan view:clear || true
RUN php artisan optimize:clear || true

EXPOSE 10000

CMD php artisan optimize:clear \
 && php artisan config:clear \
 && php artisan cache:clear \
 && php artisan route:clear \
 && php artisan view:clear \
 && php artisan migrate:fresh --seed --force \
 && php -S 0.0.0.0:$PORT -t public