FROM php:8.4-cli

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git unzip curl libzip-dev zip \
    && docker-php-ext-install pdo pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

# SQLite作成
RUN touch database/database.sqlite

# 権限
RUN chmod -R 777 storage bootstrap/cache database

# キャッシュ完全削除
RUN php artisan config:clear
RUN php artisan cache:clear
RUN php artisan route:clear
RUN php artisan view:clear
RUN php artisan optimize:clear

EXPOSE 10000

CMD php artisan migrate:fresh --seed --force && \
    php artisan config:clear && \
    php artisan cache:clear && \
    php -S 0.0.0.0:$PORT -t public