FROM php:8.2-cli

WORKDIR /var/www

# 必要なパッケージ
RUN apt-get update && apt-get install -y \
    git unzip curl libzip-dev zip \
    && docker-php-ext-install pdo pdo_mysql

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# アプリコピー
COPY . .

# 依存インストール
RUN composer install --no-dev --optimize-autoloader

# ポート
EXPOSE 10000

# 起動
CMD php artisan serve --host=0.0.0.0 --port=$PORT