<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Faq;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FaqsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('faqs')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $categories = Category::pluck('id', 'name');

        $faqs = [
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => $categories['新人向け'] ?? null,
                'question' => '出勤したら最初に確認することは何ですか？',
                'answer' => '予約状況、担当割り、引き継ぎ事項、店内の清掃状態を確認します。',
                'note' => '早番は開店準備、遅番は締め作業の確認も行います。',
                'url' => null,
                'sort_order' => 1,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => $categories['接客'] ?? null,
                'question' => 'お客様が予約時間より早く来店された場合はどう対応しますか？',
                'answer' => '受付後、待合スペースへ案内し、準備状況に応じてご案内可能な時間をお伝えします。',
                'note' => '前のお客様の状況によっては少しお待ちいただく場合があります。',
                'url' => null,
                'sort_order' => 2,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['予約'] ?? null,
                'category2_id' => $categories['受付'] ?? null,
                'question' => '予約時間に遅れそうなお客様から連絡があった場合はどうしますか？',
                'answer' => '到着予定時刻を確認し、施術時間の短縮可否や後続予約への影響を確認した上で案内します。',
                'note' => '判断が難しい場合は管理者へ確認してください。',
                'url' => null,
                'sort_order' => 3,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['予約'] ?? null,
                'category2_id' => null,
                'question' => '無断キャンセルがあった場合の対応を教えてください。',
                'answer' => '店舗ルールに沿って履歴を確認し、必要に応じて次回予約時に事前案内を行います。',
                'note' => '感情的な対応は避け、事実ベースで記録を残します。',
                'url' => null,
                'sort_order' => 4,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => null,
                'question' => '施術前のカウンセリングで必ず確認する項目は何ですか？',
                'answer' => '体調、既往歴、当日のご希望、重点的に施術したい箇所、触れられたくない箇所を確認します。',
                'note' => '禁忌事項やアレルギーも必ず確認してください。',
                'url' => null,
                'sort_order' => 5,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => $categories['新人向け'] ?? null,
                'question' => 'オイルの量はどのくらいを目安に使いますか？',
                'answer' => '部位や施術時間によりますが、摩擦が出ない程度を目安に必要量を調整します。',
                'note' => 'つけすぎると拭き取りに時間がかかるため注意してください。',
                'url' => null,
                'sort_order' => 6,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => null,
                'question' => 'お客様が強めの圧を希望された場合はどう対応しますか？',
                'answer' => '体格や体調を確認しながら無理のない範囲で調整し、痛みがないか都度確認します。',
                'note' => '強圧が危険と判断した場合は理由を伝えて調整してください。',
                'url' => null,
                'sort_order' => 7,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => null,
                'question' => '施術中に会話を控えたい雰囲気のお客様にはどう接しますか？',
                'answer' => '必要最低限の確認に留め、落ち着いて過ごしていただけるよう静かな接客を行います。',
                'note' => '無理に会話を広げないことが大切です。',
                'url' => null,
                'sort_order' => 8,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => $categories['トラブル対応'] ?? null,
                'question' => '施術中にお客様が気分不良を訴えた場合の対応を教えてください。',
                'answer' => 'すぐに施術を中止し、体勢を整えて状態を確認します。必要に応じて管理者へ報告し、医療機関受診も検討します。',
                'note' => '発生時刻、状況、対応内容を記録してください。',
                'url' => null,
                'sort_order' => 9,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => $categories['会計'] ?? null,
                'question' => 'クーポン利用時に確認することは何ですか？',
                'answer' => '利用条件、有効期限、対象メニュー、他割引との併用可否を確認します。',
                'note' => '不明な場合は自己判断せず管理者へ確認してください。',
                'url' => null,
                'sort_order' => 10,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['会計'] ?? null,
                'category2_id' => null,
                'question' => '会計時にレシートを希望されない場合はどうしますか？',
                'answer' => '発行は行った上で、不要であれば店舗ルールに従って処理します。',
                'note' => '売上記録上、未発行扱いにはしないでください。',
                'url' => null,
                'sort_order' => 11,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['会計'] ?? null,
                'category2_id' => null,
                'question' => 'レジ締めで金額差異が出た場合はどう対応しますか？',
                'answer' => '当日の会計記録、返金処理、釣銭補充履歴を確認し、差異理由を調査して管理者へ報告します。',
                'note' => '差異が少額でも必ず共有してください。',
                'url' => null,
                'sort_order' => 12,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => $categories['予約'] ?? null,
                'question' => '電話予約を受ける際の確認項目は何ですか？',
                'answer' => '希望日時、希望コース、指名有無、お名前、電話番号を確認します。',
                'note' => '新規のお客様は来店方法や注意事項も簡潔に案内します。',
                'url' => null,
                'sort_order' => 13,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => null,
                'question' => '初回来店のお客様にはどのように案内しますか？',
                'answer' => 'カウンセリングシートの記入、注意事項、施術までの流れを分かりやすくご案内します。',
                'note' => '不安が強そうな場合は急がせず丁寧に説明してください。',
                'url' => null,
                'sort_order' => 14,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => null,
                'question' => '施術後に次回予約をご案内するタイミングはいつですか？',
                'answer' => 'お会計前後でお客様の様子を見ながら、負担にならない自然なタイミングでご案内します。',
                'note' => '強い勧誘にならないよう注意してください。',
                'url' => null,
                'sort_order' => 15,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['清掃'] ?? null,
                'category2_id' => null,
                'question' => '施術後のベッド周りの清掃手順を教えてください。',
                'answer' => 'タオル交換、ベッドの拭き上げ、備品補充、床周辺の確認を行います。',
                'note' => '次のお客様をすぐ案内できる状態まで整えてください。',
                'url' => null,
                'sort_order' => 16,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['清掃'] ?? null,
                'category2_id' => null,
                'question' => '使用済みタオルの回収ルールはありますか？',
                'answer' => '店舗で定めた分別ルールに従い、指定の場所へまとめて回収します。',
                'note' => '私物や紙類が混ざらないよう注意してください。',
                'url' => null,
                'sort_order' => 17,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['トラブル対応'] ?? null,
                'category2_id' => $categories['接客'] ?? null,
                'question' => '接客中にクレームを受けた場合の基本対応を教えてください。',
                'answer' => 'まず事実確認を行い、相手の話を遮らずに聞いた上で、必要に応じて責任者へ引き継ぎます。',
                'note' => 'その場で断定的な約束はしないでください。',
                'url' => null,
                'sort_order' => 18,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['トラブル対応'] ?? null,
                'category2_id' => null,
                'question' => 'お客様の忘れ物を見つけた場合はどうしますか？',
                'answer' => '発見場所・日時・特徴を記録し、店舗ルールに従って保管します。',
                'note' => '現金や貴重品は必ず管理者へ報告してください。',
                'url' => null,
                'sort_order' => 19,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['新人向け'] ?? null,
                'category2_id' => $categories['施術'] ?? null,
                'question' => '施術に入る前に身だしなみで確認するポイントは何ですか？',
                'answer' => '髪型、爪、制服、名札、香り、清潔感を確認します。',
                'note' => 'お客様に不快感を与えないことを最優先にします。',
                'url' => null,
                'sort_order' => 20,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['新人向け'] ?? null,
                'category2_id' => $categories['受付'] ?? null,
                'question' => '電話対応で気を付けることは何ですか？',
                'answer' => '聞き取りやすい声量で、予約内容を復唱し、相違がないよう確認します。',
                'note' => '保留や折り返し時の案内も丁寧に行ってください。',
                'url' => null,
                'sort_order' => 21,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => null,
                'question' => '会話が苦手なお客様への接し方を教えてください。',
                'answer' => '必要な確認以外は無理に話しかけず、安心して過ごしていただける空気づくりを意識します。',
                'note' => '接客の丁寧さは会話量ではなく配慮で伝わります。',
                'url' => null,
                'sort_order' => 22,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['予約'] ?? null,
                'category2_id' => null,
                'question' => '指名予約が入った場合、誰に共有しますか？',
                'answer' => '担当スタッフ本人と受付担当に共有し、必要に応じて引き継ぎメモにも記載します。',
                'note' => '変更があった場合も更新漏れに注意してください。',
                'url' => null,
                'sort_order' => 23,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['会計'] ?? null,
                'category2_id' => null,
                'question' => '現金以外の支払い方法で注意することはありますか？',
                'answer' => '決済端末の処理完了を必ず確認し、売上反映漏れがないかをチェックします。',
                'note' => '通信不良時は二重決済に注意してください。',
                'url' => null,
                'sort_order' => 24,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => null,
                'question' => 'うつ伏せが辛いお客様にはどう対応しますか？',
                'answer' => '体勢変更やクッション使用など、負担が少ない方法へ調整します。',
                'note' => '体調や既往歴に応じて無理をさせないでください。',
                'url' => null,
                'sort_order' => 25,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => $categories['接客'] ?? null,
                'question' => '施術中に寒そうなお客様がいた場合はどうしますか？',
                'answer' => '室温やタオル調整の希望を伺い、必要に応じてブランケット等で対応します。',
                'note' => 'こちらから気付いて声をかけることが大切です。',
                'url' => null,
                'sort_order' => 26,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => null,
                'question' => '施術後にお手洗いの案内が必要な場合はいつ声をかけますか？',
                'answer' => 'お着替え後やお会計前など、自然な流れで必要に応じてご案内します。',
                'note' => '急かさない案内を心掛けてください。',
                'url' => null,
                'sort_order' => 27,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['清掃'] ?? null,
                'category2_id' => null,
                'question' => '開店前清掃で優先する場所はどこですか？',
                'answer' => '受付、待合、施術スペース、トイレ、共用部を優先して確認します。',
                'note' => 'お客様の目に入りやすい場所は特に丁寧に整えてください。',
                'url' => null,
                'sort_order' => 28,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['トラブル対応'] ?? null,
                'category2_id' => null,
                'question' => '予約内容の認識違いがあった場合はどう対応しますか？',
                'answer' => '予約記録を確認し、相違点を整理した上で、お客様へ丁寧に説明します。',
                'note' => 'その場しのぎではなく記録に残してください。',
                'url' => null,
                'sort_order' => 29,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['新人向け'] ?? null,
                'category2_id' => null,
                'question' => '引き継ぎメモはどのタイミングで確認しますか？',
                'answer' => '出勤直後と担当変更時、休憩明けに必ず確認します。',
                'note' => '確認漏れは接客ミスにつながるため注意してください。',
                'url' => null,
                'sort_order' => 30,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['予約'] ?? null,
                'category2_id' => $categories['接客'] ?? null,
                'question' => 'リピーターのお客様の予約時に意識することはありますか？',
                'answer' => '過去の来店履歴やご希望を確認し、できる範囲でスムーズにご案内します。',
                'note' => '前回会話の内容を覚えていると安心感につながります。',
                'url' => null,
                'sort_order' => 31,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['会計'] ?? null,
                'category2_id' => $categories['予約'] ?? null,
                'question' => '回数券や事前決済がある場合の会計処理はどうしますか？',
                'answer' => '対象コースと消化回数を確認し、利用記録を残した上で会計処理を行います。',
                'note' => '利用ミス防止のため二重確認してください。',
                'url' => null,
                'sort_order' => 32,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => null,
                'question' => '施術時間が押している場合の対応を教えてください。',
                'answer' => '現在の状況を確認し、必要であれば受付や次の担当者へ共有して調整します。',
                'note' => 'お客様への印象を損ねないよう慌てた態度は避けてください。',
                'url' => null,
                'sort_order' => 33,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => null,
                'question' => 'お客様のお見送り時に気を付けることは何ですか？',
                'answer' => '忘れ物確認、足元への配慮、次回案内の有無を確認し、最後まで丁寧に対応します。',
                'note' => '退店後も店外での所作に注意してください。',
                'url' => null,
                'sort_order' => 34,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['受付'] ?? null,
                'category2_id' => $categories['トラブル対応'] ?? null,
                'question' => '予約なしで来店されたお客様にはどう案内しますか？',
                'answer' => '空き状況を確認し、案内可能な時間や待ち時間の目安をお伝えします。',
                'note' => 'お断りする場合も丁寧な言い回しを意識してください。',
                'url' => null,
                'sort_order' => 35,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['新人向け'] ?? null,
                'category2_id' => $categories['清掃'] ?? null,
                'question' => '開店前に準備しておく備品は何がありますか？',
                'answer' => 'タオル、施術用備品、カルテ、釣銭、アメニティ類を確認します。',
                'note' => '不足がある場合は営業前に補充してください。',
                'url' => null,
                'sort_order' => 36,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['接客'] ?? null,
                'category2_id' => null,
                'question' => '会話の中で個人的な質問をされた場合はどう対応しますか？',
                'answer' => '失礼のない範囲で受け答えしつつ、必要に応じて業務の話題へ自然に戻します。',
                'note' => '個人情報に関わる内容は無理に答えないでください。',
                'url' => null,
                'sort_order' => 37,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['施術'] ?? null,
                'category2_id' => $categories['新人向け'] ?? null,
                'question' => '施術後にお客様へ伝えるホームケアの例を教えてください。',
                'answer' => '水分補給、入浴タイミング、無理をしないこと、冷え対策などを状態に応じてご案内します。',
                'note' => '専門的すぎる説明より分かりやすさを優先してください。',
                'url' => null,
                'sort_order' => 38,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['会計'] ?? null,
                'category2_id' => null,
                'question' => '領収書を希望された場合の対応を教えてください。',
                'answer' => '宛名、但し書き、金額を確認し、店舗ルールに沿って発行します。',
                'note' => '再発行可否のルールも確認しておいてください。',
                'url' => null,
                'sort_order' => 39,
                'is_visible' => 1,
            ],
            [
                'category1_id' => $categories['トラブル対応'] ?? null,
                'category2_id' => $categories['予約'] ?? null,
                'question' => '台風などで営業可否の判断が必要な場合はどうしますか？',
                'answer' => '管理者判断のもと、営業有無を決定し、必要なお客様へ順次連絡を行います。',
                'note' => 'スタッフ間でも連絡手段を統一しておきます。',
                'url' => null,
                'sort_order' => 40,
                'is_visible' => 0,
            ],
        ];

        foreach ($faqs as $faq) {
            Faq::updateOrCreate(
                ['question' => $faq['question']],
                array_merge($faq, [
                    'pdf' => null,
                    'pdf_original_name' => null,
                ])
            );
        }
    }
}